export { BooksDetail } from "./BooksDetails/BooksDetail"
export { BooksPost } from "./BooksPost/BooksPost"
export { BooksSearch } from "./BooksSearch/BooksSearch"
export { LoginPage } from "./LoginPage/LoginPage"
export { RegisterPage } from "./RegisterPage/RegisterPage"